FROM php:5-apache

ADD ssmtp.conf /etc/ssmtp/ssmtp.conf

RUN apt-get update && apt-get install -y  \
        libpq-dev \
        libzip-dev \
        libicu-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng12-dev \
        libwebp-dev \
        libxml2-dev \
        libldap2-dev \
        ssmtp \
    && docker-php-ext-install calendar \
    && docker-php-ext-enable calendar \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
        --with-webp-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo \
    && docker-php-ext-install ctype \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
    && docker-php-ext-install ldap \
    && docker-php-ext-enable ldap \
    && docker-php-ext-install json \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install pgsql \
    && docker-php-ext-install intl \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysql \
    && docker-php-ext-install soap \
    && a2enmod rewrite ext_filter vhost_alias ssl \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && curl -fsSL 'https://xcache.lighttpd.net/pub/Releases/3.2.0/xcache-3.2.0.tar.gz' -o xcache.tar.gz \
    && mkdir -p /tmp/xcache \
    && tar -xf xcache.tar.gz -C /tmp/xcache --strip-components=1 \
    && rm xcache.tar.gz \
    && docker-php-ext-configure /tmp/xcache --enable-xcache \
    && docker-php-ext-install /tmp/xcache \
    && rm -r /tmp/xcache \
    && pecl install xdebug-2.4.0 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install zip


#RUN  echo "xdebug.remote_host=$DOCKER_HOST" >> /usr/local/etc/php/conf.d/php-xdebug.ini

ADD abc.sh /usr/bin/abc
ADD php-xdebug.ini php-custom.ini php-smtp.ini /usr/local/etc/php/conf.d/
ADD _.docker.key _.docker.cert /etc/apache2/ssl/

RUN chmod 0777 /usr/bin/abc

CMD ["apache2-foreground"]